// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollingApp.Data;

#nullable disable

namespace RollingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426235803_123")]
    partial class _123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RollingApp.Models.Base.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.InitialParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("L0")
                        .HasColumnType("REAL");

                    b.Property<double>("LR")
                        .HasColumnType("REAL");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<double>("P0")
                        .HasColumnType("REAL");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("T0")
                        .HasColumnType("REAL");

                    b.Property<double>("TAU")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("VK")
                        .HasColumnType("REAL");

                    b.Property<double>("W0")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("InitialParameters");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Mill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mills");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Pass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("B0")
                        .HasColumnType("REAL");

                    b.Property<double>("B1")
                        .HasColumnType("REAL");

                    b.Property<double>("BD")
                        .HasColumnType("REAL");

                    b.Property<double>("BVR")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("H0")
                        .HasColumnType("REAL");

                    b.Property<double>("H1")
                        .HasColumnType("REAL");

                    b.Property<int>("KOD0")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KOD1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PSI")
                        .HasColumnType("REAL");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("R")
                        .HasColumnType("REAL");

                    b.Property<double>("R8")
                        .HasColumnType("REAL");

                    b.Property<double>("ROV")
                        .HasColumnType("REAL");

                    b.Property<double>("S")
                        .HasColumnType("REAL");

                    b.Property<int>("SP")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SUMX")
                        .HasColumnType("REAL");

                    b.Property<int>("StandId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TOP")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("W")
                        .HasColumnType("REAL");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StandId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MillId");

                    b.HasIndex("ParentProfileId");

                    b.HasIndex("SteelId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Stand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AKL")
                        .HasColumnType("REAL");

                    b.Property<double>("C")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DB")
                        .HasColumnType("REAL");

                    b.Property<double>("DSH")
                        .HasColumnType("REAL");

                    b.Property<double>("ETA")
                        .HasColumnType("REAL");

                    b.Property<double>("FPOD")
                        .HasColumnType("REAL");

                    b.Property<double>("IR")
                        .HasColumnType("REAL");

                    b.Property<double>("LKL")
                        .HasColumnType("REAL");

                    b.Property<double>("MDOP")
                        .HasColumnType("REAL");

                    b.Property<double>("MU")
                        .HasColumnType("REAL");

                    b.Property<int>("MillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<double>("NDVMAX")
                        .HasColumnType("REAL");

                    b.Property<double>("NDVMIN")
                        .HasColumnType("REAL");

                    b.Property<double>("NDVN")
                        .HasColumnType("REAL");

                    b.Property<double>("NNOM")
                        .HasColumnType("REAL");

                    b.Property<double>("NZ")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PDOP")
                        .HasColumnType("REAL");

                    b.Property<double>("PP")
                        .HasColumnType("REAL");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MillId");

                    b.ToTable("Stands");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Steel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("K1")
                        .HasColumnType("REAL");

                    b.Property<double>("K2")
                        .HasColumnType("REAL");

                    b.Property<double>("K3")
                        .HasColumnType("REAL");

                    b.Property<double>("K4")
                        .HasColumnType("REAL");

                    b.Property<double>("K5")
                        .HasColumnType("REAL");

                    b.Property<double>("K6")
                        .HasColumnType("REAL");

                    b.Property<double>("K7")
                        .HasColumnType("REAL");

                    b.Property<double>("K8")
                        .HasColumnType("REAL");

                    b.Property<double>("K9")
                        .HasColumnType("REAL");

                    b.Property<double>("M")
                        .HasColumnType("REAL");

                    b.Property<string>("ModifierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Steels");
                });

            modelBuilder.Entity("RollingApp.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RollingApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RollingApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RollingApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RollingApp.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RollingApp.Models.Domain.InitialParameter", b =>
                {
                    b.HasOne("RollingApp.Models.Domain.Profile", "Profile")
                        .WithOne("InitialParameter")
                        .HasForeignKey("RollingApp.Models.Domain.InitialParameter", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Pass", b =>
                {
                    b.HasOne("RollingApp.Models.Domain.Profile", "Profile")
                        .WithMany("Passes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RollingApp.Models.Domain.Stand", "Stand")
                        .WithMany()
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Profile", b =>
                {
                    b.HasOne("RollingApp.Models.Domain.Mill", "Mill")
                        .WithMany("Profiles")
                        .HasForeignKey("MillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RollingApp.Models.Domain.Profile", "ParentProfile")
                        .WithMany()
                        .HasForeignKey("ParentProfileId");

                    b.HasOne("RollingApp.Models.Domain.Steel", "Steel")
                        .WithMany()
                        .HasForeignKey("SteelId");

                    b.Navigation("Mill");

                    b.Navigation("ParentProfile");

                    b.Navigation("Steel");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Stand", b =>
                {
                    b.HasOne("RollingApp.Models.Domain.Mill", "Mill")
                        .WithMany("Stands")
                        .HasForeignKey("MillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mill");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Mill", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("Stands");
                });

            modelBuilder.Entity("RollingApp.Models.Domain.Profile", b =>
                {
                    b.Navigation("InitialParameter");

                    b.Navigation("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
